### ISSUE TITLE
[BUG] 회원가입 시 생년월일 년도 여섯자리

### ISSUE THREAD

**Issue by HyungGeun-Cho** [wafflestudio19-5/team2-web#69]
사소한 부분이긴 합니다만 회원가입을 위해 년도를 수동으로 기입 시 여섯자리까지 입력되는 것 같습니다!
<br/>

<img width="731" alt="스크린샷 2022-01-08 오후 4 19 04" src="https://user-images.githubusercontent.com/78595247/148635617-9ddd4e55-809e-4aff-8813-9fed4d70e8df.png">

**Comment by jhm1313** [comment]
![image](https://user-images.githubusercontent.com/44698831/148637717-9684d038-af28-4ffa-b913-92649e0986f0.png)

프론트 분들께 추가로 건의드리자면 회원가입시에 선택하는 날짜도 유저 프로필 update 처럼 이렇게 선택할 수 있으면 더 편할 것 같습니다!
